[package]
name = "tests"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
# itoa = "*"
# ctor = "*"
# colored = "*"
# itertools = "*"
# lazy_static = "*"
# serde_json = "*"
# as-any = "*"