[package]
name = "sww"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "*"
cfg-if = "*"
encase = { version = "*", features = ["glam"] }
glam = "*"
log = "*" # { version = "*", features = ["release_max_level_off"] }
pollster = "*"
winit = { version = "*", features = ["rwh_05"] }
env_logger = "*"
memoffset = "*"
image = "*"

[build-dependencies]
wgsl_to_wgpu = "0.6.0"
cargo-emit = "*"